FROM maven:3.9-eclipse-temurin-21-alpine

WORKDIR /app

COPY .mvn/settings.xml /root/.m2/settings.xml
COPY pom.xml ./

RUN --mount=type=cache,target=/root/.m2/repository \
    mvn dependency:resolve

EXPOSE 8080

ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-XX:+AllowRedefinitionToAddDeleteMethods"]
